

[table]
name="user2"



[field.username]
generator="random"
sourcefile="chinese_names.txt"

[field.password]
generator="depends"
source="username"

[field.password2]
generator="depends"
source="username"

[field.register_time]
generator="random"
distribution="random"
source=["1", "2", "5", "8"]

[field.last_login_time]
generator="depends"
source="username"