

[table]
name="user2"

[field.username]
generator="random"
sourcefile="chinese.names"

[field.password]
generator="depends"
depends="register_time"
method="md5"

[field.mobile]
generator="china.mobile"

[field.age]
generator="random"
source="int.range(20, 90)"

[field.leave_time]
generator="random"
source="time.range('2018-01-01 00:00:00', '2018-09-01 00:00:00')"


[field.register_time]
generator="rolling"
source="time.range('2018-01-01 00:00:00', '2019-09-01 00:00:00')"

[field.last_login_time]
generator="depends"
depends="register_time"