

[table]
name="user"



[field.username]
generator="random"
source="chinese_names.txt"

[field.password]
generator="random"
distribution="random"
source="apply(1)"

[field.register_time]
generator="random"
distribution="random"
source="apply(1)"