

[table]
name="user"



[field.username]
generator="random"
sourcefile="chinese_names.txt"

[field.password]
generator="depends"
distribution="random"
source=[1, 2, 3]

[field.register_time]
generator="random"
distribution="random"
source=["1", "2"]