

[table]
name="user2"

[field.username]
generator="random"
sourcefile="chinese.names"

[field.password]
generator="depends"
source="username"

[field.mobile]
generator="china.mobile"
depends="username"

[field.age]
generator="random"
source="range(20, 90)"


[field.register_time]
generator="random"
distribution="random"
source=["1", "2", "5", "8"]

[field.last_login_time]
generator="depends"
source="username"