
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '505CE2EFDDCCF2F001CBB31B46A23629'
    
_lr_action_items = {'VLINE':([13,19,23,26,39,51,52,53,54,55,66,],[-35,-9,-24,40,-23,-16,60,-15,-18,-10,-17,]),'RBRACKET':([13,16,17,18,19,21,22,23,24,26,27,36,37,39,48,55,56,59,60,62,],[-35,-6,-2,-8,-9,-1,-5,-24,-4,-3,-7,48,-13,-23,-14,-10,62,-12,-19,-11,]),'DOT':([7,19,26,33,34,35,55,71,],[15,-9,41,15,46,47,-10,41,]),'INT':([12,20,38,42,49,74,75,76,77,78,79,],[16,16,16,56,16,16,16,16,16,16,16,]),'RPAREN':([12,13,16,17,18,19,21,22,23,24,25,26,27,28,29,39,48,50,55,60,62,64,68,69,80,81,82,83,84,85,86,],[23,-35,-6,-2,-8,-9,-1,-5,-24,-4,39,-3,-7,-20,-22,-23,-14,-21,-10,-19,-11,67,73,-32,-31,-26,-25,-30,-29,-28,-27,]),'STR':([12,20,38,49,74,75,76,77,78,79,],[18,18,18,18,18,18,18,18,18,18,]),'$end':([1,2,8,9,10,11,43,44,45,],[0,-45,-44,-41,-43,-42,-38,-39,-40,]),'NAME':([0,1,2,8,9,10,11,12,14,15,20,38,40,41,43,44,45,46,47,49,61,64,72,74,75,76,77,78,79,],[7,7,-45,-44,-41,-43,-42,19,33,35,19,19,53,55,-38,-39,-40,57,58,19,53,19,19,19,19,19,19,19,19,]),'LPAREN':([6,57,58,],[12,12,64,]),'LT':([19,55,71,],[-9,-10,78,]),'GT':([19,55,71,],[-9,-10,79,]),'EQU':([7,19,55,70,71,],[14,-9,-10,74,75,]),'LBRACKET':([12,19,20,26,38,49,55,74,75,76,77,78,79,],[20,-9,20,42,20,20,-10,20,20,20,20,20,20,]),'LTE':([19,55,71,],[-9,-10,76,]),'SEMI':([3,4,5,13,23,30,31,32,39,63,65,67,73,],[9,10,11,-35,-24,43,44,45,-23,-36,-37,-34,-33,]),'COMMA':([13,16,17,18,19,21,22,23,24,25,26,27,28,29,36,37,39,48,50,51,52,53,54,55,59,60,62,66,68,69,80,81,82,83,84,85,86,],[-35,-6,-2,-8,-9,-1,-5,-24,-4,38,-3,-7,-20,-22,49,-13,-23,-14,-21,-16,61,-15,-18,-10,-12,-19,-11,-17,72,-32,-31,-26,-25,-30,-29,-28,-27,]),'BUILDIN':([0,1,2,8,9,10,11,12,14,15,20,38,40,43,44,45,49,61,64,72,74,75,76,77,78,79,],[6,6,-45,-44,-41,-43,-42,6,6,34,6,6,6,-38,-39,-40,6,6,70,70,6,6,6,6,6,6,]),'GTE':([19,55,71,],[-9,-10,77,]),'FLOAT':([12,20,38,49,74,75,76,77,78,79,],[27,27,27,27,27,27,27,27,27,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'list':([12,20,38,49,74,75,76,77,78,79,],[22,22,22,22,22,22,22,22,22,22,]),'statements':([0,],[1,]),'filter_items':([40,],[52,]),'arrval':([12,20,38,49,74,75,76,77,78,79,],[17,17,17,17,17,17,17,17,17,17,]),'list_items':([20,],[36,]),'condition':([64,72,],[69,80,]),'statement':([0,1,],[2,8,]),'params':([6,57,],[13,63,]),'condition_list':([64,],[68,]),'conditions':([58,],[65,]),'func':([0,1,12,14,20,38,40,49,61,74,75,76,77,78,79,],[3,3,24,30,24,24,51,24,51,24,24,24,24,24,24,]),'param_list':([12,],[25,]),'redis_query':([0,1,14,],[4,4,32,]),'symbol':([12,20,38,49,64,72,74,75,76,77,78,79,],[26,26,26,26,71,71,26,26,26,26,26,26,]),'query':([0,1,14,],[5,5,31,]),'rvalue':([12,20,38,49,74,75,76,77,78,79,],[28,37,28,59,81,82,83,84,85,86,]),'filter_item':([40,61,],[54,66,]),'param':([12,38,],[29,50,]),'filter':([12,20,38,49,74,75,76,77,78,79,],[21,21,21,21,21,21,21,21,21,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('rvalue -> filter','rvalue',1,'p_rvalue','simplequery_parser.py',104),
  ('rvalue -> arrval','rvalue',1,'p_rvalue','simplequery_parser.py',105),
  ('rvalue -> symbol','rvalue',1,'p_rvalue','simplequery_parser.py',106),
  ('rvalue -> func','rvalue',1,'p_rvalue','simplequery_parser.py',107),
  ('rvalue -> list','rvalue',1,'p_rvalue','simplequery_parser.py',108),
  ('rvalue -> INT','rvalue',1,'p_rvalue','simplequery_parser.py',109),
  ('rvalue -> FLOAT','rvalue',1,'p_rvalue','simplequery_parser.py',110),
  ('rvalue -> STR','rvalue',1,'p_rvalue','simplequery_parser.py',111),
  ('symbol -> NAME','symbol',1,'p_symbol','simplequery_parser.py',115),
  ('symbol -> symbol DOT NAME','symbol',3,'p_symbol','simplequery_parser.py',116),
  ('arrval -> symbol LBRACKET INT RBRACKET','arrval',4,'p_arrval','simplequery_parser.py',124),
  ('list_items -> list_items COMMA rvalue','list_items',3,'p_list_items','simplequery_parser.py',130),
  ('list_items -> rvalue','list_items',1,'p_list_items','simplequery_parser.py',131),
  ('list -> LBRACKET list_items RBRACKET','list',3,'p_list','simplequery_parser.py',140),
  ('filter_item -> NAME','filter_item',1,'p_filter_item','simplequery_parser.py',145),
  ('filter_item -> func','filter_item',1,'p_filter_item','simplequery_parser.py',146),
  ('filter_items -> filter_items COMMA filter_item','filter_items',3,'p_filter_items','simplequery_parser.py',150),
  ('filter_items -> filter_item','filter_items',1,'p_filter_items','simplequery_parser.py',151),
  ('filter -> symbol VLINE filter_items VLINE','filter',4,'p_filter','simplequery_parser.py',159),
  ('param -> rvalue','param',1,'p_param','simplequery_parser.py',165),
  ('param_list -> param_list COMMA param','param_list',3,'p_param_list','simplequery_parser.py',169),
  ('param_list -> param','param_list',1,'p_param_list','simplequery_parser.py',170),
  ('params -> LPAREN param_list RPAREN','params',3,'p_params','simplequery_parser.py',179),
  ('params -> LPAREN RPAREN','params',2,'p_params','simplequery_parser.py',180),
  ('condition -> symbol EQU rvalue','condition',3,'p_condition','simplequery_parser.py',188),
  ('condition -> BUILDIN EQU rvalue','condition',3,'p_condition','simplequery_parser.py',189),
  ('condition -> symbol GT rvalue','condition',3,'p_condition','simplequery_parser.py',190),
  ('condition -> symbol LT rvalue','condition',3,'p_condition','simplequery_parser.py',191),
  ('condition -> symbol GTE rvalue','condition',3,'p_condition','simplequery_parser.py',192),
  ('condition -> symbol LTE rvalue','condition',3,'p_condition','simplequery_parser.py',193),
  ('condition_list -> condition_list COMMA condition','condition_list',3,'p_condition_list','simplequery_parser.py',197),
  ('condition_list -> condition','condition_list',1,'p_condition_list','simplequery_parser.py',198),
  ('conditions -> LPAREN condition_list RPAREN','conditions',3,'p_conditions','simplequery_parser.py',206),
  ('conditions -> LPAREN RPAREN','conditions',2,'p_conditions','simplequery_parser.py',207),
  ('func -> BUILDIN params','func',2,'p_func','simplequery_parser.py',215),
  ('redis_query -> NAME DOT BUILDIN DOT NAME params','redis_query',6,'p_redis_query','simplequery_parser.py',219),
  ('query -> NAME DOT NAME DOT NAME conditions','query',6,'p_query','simplequery_parser.py',223),
  ('statement -> NAME EQU func SEMI','statement',4,'p_statement','simplequery_parser.py',228),
  ('statement -> NAME EQU query SEMI','statement',4,'p_statement','simplequery_parser.py',229),
  ('statement -> NAME EQU redis_query SEMI','statement',4,'p_statement','simplequery_parser.py',230),
  ('statement -> func SEMI','statement',2,'p_statement','simplequery_parser.py',231),
  ('statement -> query SEMI','statement',2,'p_statement','simplequery_parser.py',232),
  ('statement -> redis_query SEMI','statement',2,'p_statement','simplequery_parser.py',233),
  ('statements -> statements statement','statements',2,'p_statements','simplequery_parser.py',245),
  ('statements -> statement','statements',1,'p_statements','simplequery_parser.py',246),
]
